In [ ]:
import pandas as pd
from sklearn.naive_bayes import CategoricalNB
from sklearn.preprocessing import LabelEncoder

In [ ]:
data = {
    'Age' : ['youth', 'youth', 'middle', 'senior', 'senior', 'middle', 'senior','youth', 'youth', 'senior', 'youth', 'middle', 'middle', 'senior'],
    'Income' : ['high', 'high', 'high', 'medium', 'low', 'low', 'low', 'medium', 'low', 'medium', 'medium', 'medium', 'high','medium'],
    'Student' : ['no', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'no', 'yes','no'],
    'CreditRating' : ['fair', 'excellent', 'fair', 'fair', 'fair', 'excellent', 'excellent', 'fair','fair', 'fair', 'excellent', 'excellent', 'fair','excellent'],
    'BuysComputer' : ['no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'no','yes']
}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

       Age  Income Student CreditRating BuysComputer
0    youth    high      no         fair           no
1    youth    high      no    excellent           no
2   middle    high      no         fair          yes
3   senior  medium      no         fair          yes
4   senior     low     yes         fair          yes
5   middle     low     yes    excellent           no
6   senior     low     yes    excellent          yes
7    youth  medium      no         fair           no
8    youth     low     yes         fair          yes
9   senior  medium     yes         fair          yes
10   youth  medium     yes    excellent          yes
11  middle  medium      no    excellent          yes
12  middle    high     yes         fair           no
13  senior  medium      no    excellent          yes

In [ ]:
le = {}
df_enc = df.copy()
for col in df.columns:
  le[col] = LabelEncoder()
  df_enc[col] = le[col].fit_transform(df[col])

In [ ]:
df_enc

    Age  Income  Student  CreditRating  BuysComputer
0     2       0        0             1             0
1     2       0        0             0             0
2     0       0        0             1             1
3     1       2        0             1             1
4     1       1        1             1             1
5     0       1        1             0             0
6     1       1        1             0             1
7     2       2        0             1             0
8     2       1        1             1             1
9     1       2        1             1             1
10    2       2        1             0             1
11    0       2        0             0             1
12    0       0        1             1             0
13    1       2        0             0             1

In [ ]:
x = df_enc[['Age','Income','Student','CreditRating']]
y = df_enc['BuysComputer']

In [ ]:
x

    Age  Income  Student  CreditRating
0     2       0        0             1
1     2       0        0             0
2     0       0        0             1
3     1       2        0             1
4     1       1        1             1
5     0       1        1             0
6     1       1        1             0
7     2       2        0             1
8     2       1        1             1
9     1       2        1             1
10    2       2        1             0
11    0       2        0             0
12    0       0        1             1
13    1       2        0             0

In [ ]:
y

0     0
1     0
2     1
3     1
4     1
5     0
6     1
7     0
8     1
9     1
10    1
11    1
12    0
13    1
Name: BuysComputer, dtype: int64

In [ ]:
model = CategoricalNB()
algo=model.fit(x,y)

In [4]:
test =[['Youth','Medium','Yes','Fair']]

In [5]:
test

[['Youth', 'Medium', 'Yes', 'Fair']]

In [16]:
print("\n--------Prediction---------------------------")
for t in test:
  row = [[
      le['Age'].transform([t[0].lower()])[0],
      le['Income'].transform([t[1].lower()])[0],
      le['Student'].transform([t[2].lower()])[0],
      le['CreditRating'].transform([t[3].lower()])[0]
  ]]

  pred = le['BuysComputer'].inverse_transform(algo.predict(row))[0]
  prob = model.predict_proba(row)[0]
  print(f"Input: Age={t[0]}, Income={t[1]}, Student={t[2]}, CreditRating={t[3]}")
  print(f"Result: BuysComputer={pred}")
  print(f"P(No) = {prob[0]:.4f}")
  print(f"P(Yes) = {prob[1]:.4f}")

--------Prediction---------------------------

NameError: name 'le' is not defined

In [ ]:
from sklearn.metrics import accuracy_score
y_pred = model.predict(x)
print(f"\nTraining Accuracy: {accuracy_score(y,y_pred)*100:.2f}%")

Training Accuracy: 78.57%